services:
  db:
    image: postgres:14
    container_name: outfitease-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: hiroki
      POSTGRES_PASSWORD: Usausa127!
      POSTGRES_DB: outfitease
    volumes:
      - outfitease_pgdata:/var/lib/postgresql/data

volumes:
  outfitease_pgdata:
